steps:
  - simple_align: {}
  - imports: {}
  - language_pragmas: {}
  - trailing_whitespace: {}

language_extensions:
  - ExplicitForAll
  - FlexibleContexts # stylish-haskell bug, see jaspervdj/stylish-haskell#230
  - MultiParamTypeClasses # stylish-haskell bug, see jaspervdj/stylish-haskell#103 and haskell-suite/haskell-src-exts#304
